# Test pipeline to check Microsoft-hosted agent access
name: 'Test-Hosted-Agent-$(Date:yyyyMMdd)$(Rev:.r)'

trigger: none  # Manual only for testing

# Direct pool specification - no parameters
pool:
  vmImage: 'windows-latest'

variables:
  - name: testVar
    value: 'testing'

jobs:
- job: TestMSHosted
  displayName: 'Test Microsoft Hosted Windows Agent'
  
  steps:
  - task: PowerShell@2
    displayName: 'Agent Information'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "🔍 Testing Microsoft-Hosted Agent Access" -ForegroundColor Cyan
        Write-Host "Agent Name: $(Agent.Name)" -ForegroundColor Yellow
        Write-Host "Agent OS: $(Agent.OS)" -ForegroundColor Yellow  
        Write-Host "Agent Version: $(Agent.Version)" -ForegroundColor Yellow
        Write-Host "Build Number: $(Build.BuildNumber)" -ForegroundColor Green
        Write-Host "✅ If you see this, Microsoft-hosted agents are working!" -ForegroundColor Green

  - task: PowerShell@2
    displayName: 'Test Basic Commands'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Testing basic PowerShell commands..." -ForegroundColor Cyan
        Get-Location
        Get-Date
        Write-Host "✅ Basic commands working!" -ForegroundColor Green